// <auto-generated />
using System;
using HybridSlicer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HybridSlicer.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427214607_MachineProfileExtruderFields")]
    partial class MachineProfileExtruderFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("HybridSlicer.Domain.Entities.BrandingSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BrandingSettings");
                });

            modelBuilder.Entity("HybridSlicer.Domain.Entities.CncTool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DiameterMm")
                        .HasColumnType("REAL");

                    b.Property<int>("FluteCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FluteLengthMm")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxDepthOfCutMm")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("RecommendedFeedMmPerMin")
                        .HasColumnType("REAL");

                    b.Property<int>("RecommendedRpm")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ShankDiameterMm")
                        .HasColumnType("REAL");

                    b.Property<double>("ToolLengthMm")
                        .HasColumnType("REAL");

                    b.Property<string>("ToolMaterial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CncTools");
                });

            modelBuilder.Entity("HybridSlicer.Domain.Entities.CustomGCodeBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("GCodeContent")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CustomGCodeBlocks");
                });

            modelBuilder.Entity("HybridSlicer.Domain.Entities.HybridProcessPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MachineEveryNLayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OverallSafetyStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPrintLayers")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HybridProcessPlans");
                });

            modelBuilder.Entity("HybridSlicer.Domain.Entities.MachineProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("BedDepthMm")
                        .HasColumnType("REAL");

                    b.Property<double>("BedHeightMm")
                        .HasColumnType("REAL");

                    b.Property<double>("BedWidthMm")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtruderCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LeftBedEdgeOffsetMm")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NozzleYOffsetsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]")
                        .HasColumnName("NozzleYOffsets");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RightBedEdgeOffsetMm")
                        .HasColumnType("REAL");

                    b.Property<double>("SafeClearanceHeightMm")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MachineProfiles");
                });

            modelBuilder.Entity("HybridSlicer.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BedTempMaxDegC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BedTempMinDegC")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DensityGPerCm3")
                        .HasColumnType("REAL");

                    b.Property<double>("DiameterMm")
                        .HasColumnType("REAL");

                    b.Property<int>("GlassTransitionTempDegC")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrintTempMaxDegC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrintTempMinDegC")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("HybridSlicer.Domain.Entities.PrintJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CncToolId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("HybridGCodePath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("InfillDensityPct")
                        .HasColumnType("REAL");

                    b.Property<string>("InfillPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MachineProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrintGCodePath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrintProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StlFilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupportPlacement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolpathGCodePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalPrintLayers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrintJobs");
                });

            modelBuilder.Entity("HybridSlicer.Domain.Entities.PrintProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BedTemperatureDegC")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BrimEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrimLineCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CoolingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoolingFanSpeedPct")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("FilamentDiameterMm")
                        .HasColumnType("REAL");

                    b.Property<double>("FirstLayerSpeedMmS")
                        .HasColumnType("REAL");

                    b.Property<double>("InfillDensityPct")
                        .HasColumnType("REAL");

                    b.Property<string>("InfillPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("InfillSpeedMmS")
                        .HasColumnType("REAL");

                    b.Property<double>("InnerWallSpeedMmS")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LayerHeightMm")
                        .HasColumnType("REAL");

                    b.Property<double>("LineWidthMm")
                        .HasColumnType("REAL");

                    b.Property<double>("MaterialFlowPct")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("NozzleDiameterMm")
                        .HasColumnType("REAL");

                    b.Property<bool>("PelletModeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PrintSpeedMmS")
                        .HasColumnType("REAL");

                    b.Property<int>("PrintTemperatureDegC")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RetractLengthMm")
                        .HasColumnType("REAL");

                    b.Property<double>("RetractSpeedMmS")
                        .HasColumnType("REAL");

                    b.Property<bool>("SupportEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SupportOverhangAngleDeg")
                        .HasColumnType("REAL");

                    b.Property<string>("SupportType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TopBottomLayers")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TravelSpeedMmS")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("VirtualFilamentDiameterMm")
                        .HasColumnType("REAL");

                    b.Property<int>("WallCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WallSpeedMmS")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("PrintProfiles");
                });

            modelBuilder.Entity("HybridSlicer.Domain.Entities.ProcessStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CncGCodeFragment")
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomGCodeBlockId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndLayer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrintGCodeFragment")
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT");

                    b.Property<string>("SafetyNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SafetyStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartLayer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ToolId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("ProcessSteps");
                });

            modelBuilder.Entity("HybridSlicer.Domain.Entities.MachineProfile", b =>
                {
                    b.OwnsMany("HybridSlicer.Domain.Entities.ExtruderAssignment", "ExtruderAssignments", b1 =>
                        {
                            b1.Property<Guid>("MachineProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Duty")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("ExtruderIndex")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MachineProfileId", "Id");

                            b1.ToTable("MachineProfiles");

                            b1.ToJson("ExtruderAssignments");

                            b1.WithOwner()
                                .HasForeignKey("MachineProfileId");
                        });

                    b.OwnsMany("HybridSlicer.Domain.Entities.ToolOffset", "ToolOffsets", b1 =>
                        {
                            b1.Property<Guid>("MachineProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT");

                            b1.Property<double>("LengthOffsetMm")
                                .HasColumnType("REAL");

                            b1.Property<double>("OffsetX")
                                .HasColumnType("REAL");

                            b1.Property<double>("OffsetY")
                                .HasColumnType("REAL");

                            b1.Property<double>("OffsetZ")
                                .HasColumnType("REAL");

                            b1.Property<double>("RadiusOffsetMm")
                                .HasColumnType("REAL");

                            b1.Property<int>("ToolIndex")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MachineProfileId", "Id");

                            b1.ToTable("MachineProfiles");

                            b1.ToJson("ToolOffsets");

                            b1.WithOwner()
                                .HasForeignKey("MachineProfileId");
                        });

                    b.OwnsOne("HybridSlicer.Domain.ValueObjects.MachineOffset", "CncOffset", b1 =>
                        {
                            b1.Property<Guid>("MachineProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("RotationDeg")
                                .HasColumnType("REAL")
                                .HasColumnName("CncOffsetRotDeg");

                            b1.Property<double>("X")
                                .HasColumnType("REAL")
                                .HasColumnName("CncOffsetX");

                            b1.Property<double>("Y")
                                .HasColumnType("REAL")
                                .HasColumnName("CncOffsetY");

                            b1.Property<double>("Z")
                                .HasColumnType("REAL")
                                .HasColumnName("CncOffsetZ");

                            b1.HasKey("MachineProfileId");

                            b1.ToTable("MachineProfiles");

                            b1.WithOwner()
                                .HasForeignKey("MachineProfileId");
                        });

                    b.Navigation("CncOffset")
                        .IsRequired();

                    b.Navigation("ExtruderAssignments");

                    b.Navigation("ToolOffsets");
                });

            modelBuilder.Entity("HybridSlicer.Domain.Entities.ProcessStep", b =>
                {
                    b.HasOne("HybridSlicer.Domain.Entities.HybridProcessPlan", null)
                        .WithMany("Steps")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HybridSlicer.Domain.Entities.HybridProcessPlan", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
